import { prisma } from '../src/lib/prisma';
import { createDbBackup } from '../src/lib/dbBackup';
import { parseContributorHtml } from '../src/lib/contributorParser';

// Adobe Contributor HTML provided by the user in chat
const contributorHtml = `
<div data-t="portfolio-page-assets-list">
<div title="10 Important historical event timeline infographic brochure." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as2.ftcdn.net/jpg/05/69/02/95/220_F_569029521_nvb43XQC5cbHQVo5saCEfXxjjGpPZf8d.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">1,410</span></div></div></div>
<div title="Workflow lines infographic. The pie chart is divided into 6 parts. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as2.ftcdn.net/jpg/06/36/37/61/220_F_636376104_D23xAzwQxqzftwPKegxYHtrR33zKpwPw.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">1,399</span></div></div></div>
<div title="6 process infographic design template. diagram, annual report, business presentation, and organization. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as2.ftcdn.net/jpg/06/38/90/23/220_F_638902325_PjCIp1g2NhKqRJ7YTwkhqoSKpz6KMlmz.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">1,245</span></div></div></div>
<div title="Business presentation with white arrows on yellow background template. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as2.ftcdn.net/jpg/06/10/99/25/220_F_610992545_I13JhjSkY44B1XJkEA8vRM4HgCRgu8WV.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">896</span></div></div></div>
<div title="5 Elements Infographic design template. Presentation, Report, Banner, Poster, Strategy and Plan. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as2.ftcdn.net/jpg/10/56/56/35/220_F_1056563551_3vyYxEUwV2DiKlc7Hpe9gYiWqAKcmU8r.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">827</span></div></div></div>
<div title="Business presentation 3 option with white upward oblique arrows on yellow background template. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as1.ftcdn.net/jpg/06/21/57/98/220_F_621579842_uF9uZprIRlWJCr2Lexo9qrQZXVVWtMx5.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">799</span></div></div></div>
<div title="hacker criminal security internet" class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as1.ftcdn.net/jpg/01/75/52/40/220_F_175524050_hSE3JhBTTNK7JKZcuC6JMD0doezbvm3T.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">648</span></div></div></div>
<div title="Laptop and smartphone mockup white screen display for website banner. Vector Illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as2.ftcdn.net/jpg/05/33/56/79/220_F_533567919_AII5dLuVCxHCI9IhFaZm5TucNaVvyj4t.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">645</span></div></div></div>
<div title="Collection of the anniversary celebration golden logo style. Celebration company event. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as2.ftcdn.net/jpg/06/35/50/53/220_F_635505344_DH40kCkkkpzH0ZzDppqfpWD9BQf0OKcm.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">633</span></div></div></div>
<div title="Company milestone 10 years timeline infographic vector" class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as1.ftcdn.net/jpg/05/06/39/56/220_F_506395673_QN333f56n5i7UlIDQX1CsxQDcdY0JMkp.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">623</span></div></div></div>
<div title="Infographic arrow cycle with four steps or options. Process, Strategy, Planning, Chart. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as2.ftcdn.net/jpg/06/06/82/87/220_F_606828761_ZHfqrvfS42xWUjbpSgbjoagcG1DnFNMS.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">608</span></div></div></div>
<div title="Infographic business presentation 5 options to goal. Infographic Arrows. Strategy, Marketing, Report. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as2.ftcdn.net/jpg/06/15/65/15/220_F_615651530_inn4ao7trem9SwP7yFP6SFNCzW7xNDdC.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">595</span></div></div></div>
<div title="Sales and marketing funnel strategies infographic template. Business Presentation. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as1.ftcdn.net/jpg/06/25/57/60/220_F_625576017_6fBSuHIIeVDPVGmEc6Ru9tRPc5FdehzA.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">510</span></div></div></div>
<div title="7 steps infographic poster or brochure. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as1.ftcdn.net/jpg/06/18/17/50/220_F_618175059_V9sUdg6htmoYTTpF5mw91GceQsfiHHpg.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">497</span></div></div></div>
<div title="Business timeline 7 years. Infographic design template for business. Milestone, Anniversary, Planning, and Roadmap. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as2.ftcdn.net/jpg/06/57/70/45/220_F_657704542_NyoPmd4krcLHtjUcPDdduW2f6fZmOArd.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">495</span></div></div></div>
<div title="Timeline Infographic Company History Milestones" class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as1.ftcdn.net/jpg/02/25/21/74/220_F_225217403_T9mrz4ccRjdrDGQHJguNL66sLjD2NFSh.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">484</span></div></div></div>
<div title="5th Anniversary timeline infographic template on the road to success. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as1.ftcdn.net/jpg/05/77/25/40/220_F_577254017_9UM25wCftLqam0lHTFUpLjEYsFPvEGeD.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">459</span></div></div></div>
<div title="timeline company history anniversary 10 year blue wave color circle" class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as2.ftcdn.net/jpg/01/22/05/93/220_F_122059355_pwf2WTm8b0VM3DvfuTCZtoRKk5qtQnX6.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">438</span></div></div></div>
<div title="3 process infographic arrows design template. Planning, Marketing and Business presentation. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as1.ftcdn.net/jpg/08/01/90/80/220_F_801908005_U0OlRk613UtLOYea88B8xMLLbC9QvKac.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">424</span></div></div></div>
<div title="Set of clouds isolated on blue sky" class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as2.ftcdn.net/jpg/04/69/55/17/220_F_469551720_SYQ9QtOesJoH5qFUoaQXkwiFOPqSCzQs.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">422</span></div></div></div>
<div title="3 steps infographic arrow design template. Business Presentation, Plan, Marketing and Strategy. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as1.ftcdn.net/jpg/10/73/13/18/220_F_1073131856_15okqUDFjmjmH23NamKtOCwpObIF1Dv1.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">383</span></div></div></div>
<div title="Business visualization infographic circle design template with 5 options, steps or processes. Business presentation." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as2.ftcdn.net/jpg/13/73/64/41/220_F_1373644132_yKHMOy1WHNZsimYmR0LQBnHegv0ddDjJ.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">379</span></div></div></div>
<div title="Infographic semicircle 7 processes to success." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as1.ftcdn.net/jpg/05/69/03/24/220_F_569032404_zmKoqESDIaPP32G3vNdLrCXKaQlyJBQf.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">365</span></div></div></div>
<div title="6 alternating vertical infographic options design template. Business presentation, Banner, Brochure, Poster and Planning. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as2.ftcdn.net/jpg/09/49/53/51/220_F_949535178_D0Nbgkad0sNNgDGu3WldFy6wcdHxowuT.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">358</span></div></div></div>
<div title="Infographic frame with four steps or options. Presentation, Process, Strategy and Planning." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as2.ftcdn.net/jpg/15/68/89/17/220_F_1568891754_8AcHrikcErhZNT3Cb5hvrtPVmJaaMojs.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">310</span></div></div></div>
<div title="5 steps business growth infographic layer on black background. Business presentation, Banner, Brochure, Report and Strategy. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as1.ftcdn.net/jpg/10/46/22/92/220_F_1046229217_ucvM1lxi2DykKXXjZkWHItnCdb66hktb.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">302</span></div></div></div>
<div title="6 Steps circle and curve horizontal infographic design for your business data. Presentation, Timeline, Workflow, Marketing and Strategy. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as1.ftcdn.net/jpg/19/29/09/20/220_F_1929092005_RNgB2Y8VEW1YKVHxCTyFeTHRAooOJsr8.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">284</span></div></div></div>
<div title="Sales and marketing funnel strategies 4 stages infographic template. Business Presentation, Strategy, Plan and Plan. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as1.ftcdn.net/jpg/15/02/38/32/220_F_1502383224_80WfFHqVba199hE8GwR3SOddgk6jCsqS.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">267</span></div></div></div>
<div title="Infographic hexagon cycle. The pie chart is divided into 6 parts. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as1.ftcdn.net/jpg/06/24/73/00/220_F_624730011_tlM3cXlAnOzPQtmzUspN0rQhgOQv5ojX.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">266</span></div></div></div>
<div title="Arrow up and down banner yellow background" class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as2.ftcdn.net/jpg/05/09/94/73/220_F_509947375_60SPPiKC8cvIbmMsFC9W9pMFo8SfTRvD.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">261</span></div></div></div>
<div title="Business presentation with arrow movement template. Business moves forward. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as1.ftcdn.net/jpg/06/29/10/82/220_F_629108223_FiWgzSt193AI3a51dyRWsx7NzdAyuwec.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">242</span></div></div></div>
<div title="4 process infographic arrows design template. Planning, Marketing, Strategy and Business presentation. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as1.ftcdn.net/jpg/09/81/97/24/220_F_981972400_ikEO0cOAenRYaPVzoH5ULnhX290y8xu8.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">241</span></div></div></div>
<div title="Business presentation with oblique-up arrows on yellow background template. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as2.ftcdn.net/jpg/06/21/57/97/220_F_621579738_viVuLrIvkCflzBEAg7XC8ZaDc5nbNPbc.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">234</span></div></div></div>
<div title="Infographic diagram 8 options or steps. Mindmap, Process, Template. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as2.ftcdn.net/jpg/05/83/48/59/220_F_583485973_h5iUNGQC1G7z2ertdlZ5od1t71TPfsAg.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">233</span></div></div></div>
<div title="Infographic 5 arrow options overlapping. Crossroads 5 options. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as2.ftcdn.net/jpg/06/15/65/17/220_F_615651750_IBor85lGaoqpB1FtxKlm7j13GCNBoTVz.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">227</span></div></div></div>
<div title="10 years timeline of business design template. Business presentation, Roadmap, Milestone, Strategy and Business planning. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as1.ftcdn.net/jpg/15/94/34/34/220_F_1594343475_YlT2KtnIqUqIPEJ2SCOoGORRr9klO4ec.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">220</span></div></div></div>
<div title="Business visualization infographic semi circle design template with 4 options or steps. Business presentation, Report, Banner, and Planning. Vector illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as2.ftcdn.net/jpg/09/46/12/13/220_F_946121399_u8XSS9P7d2Vr3fG4Hk82A5pP5MvMFBvV.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">218</span></div></div></div>
<div title="Infographic roadmap design template. Business timeline 5 steps to success. Presentation, Milestone, Annual report, data and information. Vector Illustration." class="left"><div class="margin-small content-thumbnail-wrapper"><div class="content-thumbnail"><img src="https://as1.ftcdn.net/jpg/10/75/95/56/220_F_1075955624_UZ88OIlTd8m6wQ7DJ0xwrpOu0W1RLiEe.jpg"></div><div class="container-inline-block vertical-align-top flex-even"><div class="grey mountain-mist-text text-up text-small">downloads</div><span class="text-medium light">210</span></div></div></div>
</div>
`;

async function main() {
  console.log('--- Step 1: Creating Database Backup ---');
  const backup = await createDbBackup();
  console.log('DB Backup created:', backup);

  console.log('--- Step 2: Resetting Placeholder 345672354 downloads to 0 ---');
  await prisma.image.updateMany({
    where: { asId: '345672354' },
    data: {
      asDownloads: 0,
      totalDownloads: 0,
    },
  });
  console.log('Placeholder 345672354 downloads reset to 0');

  console.log('--- Step 3: Parsing Contributor HTML ---');
  const parsedItems = parseContributorHtml(contributorHtml);
  console.log(`Parsed ${parsedItems.length} items from HTML`);

  let updatedCount = 0;
  for (const item of parsedItems) {
    if (!item.asId || item.downloads === undefined) continue;

    const existing = await prisma.image.findFirst({
      where: { asId: item.asId },
      select: { id: true, code: true, ssDownloads: true, asDownloads: true },
    });

    if (existing) {
      const newTotal = (existing.ssDownloads || 0) + item.downloads;
      await prisma.image.update({
        where: { id: existing.id },
        data: {
          asDownloads: item.downloads,
          totalDownloads: newTotal,
        },
      });
      updatedCount++;
    }
  }

  console.log(`Successfully updated ${updatedCount} artwork downloads in database!`);
}

main()
  .catch((err) => {
    console.error('Migration failed:', err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
